version: '3'

services:
  postgres:
    image: postgres:14.3
    container_name: postgres-container
    restart: always
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}      

  phppgadmin:
    image: dpage/pgadmin4
    container_name: phppgadmin-container
    restart: always
    environment:        
      PGADMIN_DEFAULT_EMAIL: ingeniero.wb@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0  # Escuchar en todas las interfaces
      PGADMIN_DEFAULT_SERVER: postgres-container  # Nombre del servicio PostgreSQL
    ports:
      - "${PHPPGADMIN_PORT}:80"
    depends_on:
        - postgres