version: '3'

services:
  postgres:
    image: postgres:14.3
    container_name: postgres-container
    restart: always
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}  