// Generated by https://quicktype.io

export interface CloudinaryResponse {
    public_id:     string;
    version:       number;
    signature:     string;
    width:         number;
    height:        number;
    format:        string;
    resource_type: string;
    created_at:    string;
    bytes:         number;
    type:          string;
    etag:          string;
    url:           string;
    secure_url:    string;
}
